name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to npmjs (unscoped)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          CURRENT=$(node -p "require('./package.json').version")
          PUBLISHED=$(npm view buildworks-ai-decision-mcp version || echo '0.0.0')
          echo "npmjs current=${CURRENT} published=${PUBLISHED}"
          if [ "$CURRENT" != "$PUBLISHED" ]; then
            npm publish --loglevel=verbose
          else
            echo "Skip npmjs publish: ${CURRENT} already published"
          fi

      - name: Configure GitHub Packages registry
        run: |
          cp package.json package.npm.json
          node -e '
            const fs = require("fs");
            const pkg = JSON.parse(fs.readFileSync("package.json", "utf8"));
            pkg.name = "@buildworksai/decision-mcp";
            pkg.publishConfig = { registry: "https://npm.pkg.github.com" };
            fs.writeFileSync("package.json", JSON.stringify(pkg, null, 2));
          '
          echo "@buildworksai:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc

      - name: Setup Node.js for GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com
          scope: '@buildworksai'

      - name: Publish to GitHub Packages (optional)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Attempting to publish to GitHub Packages..."
          CURRENT=$(node -p "require('./package.json').version")
          echo "Current version: ${CURRENT}"
          
          # Try to publish to GitHub Packages, but don't fail the workflow if it doesn't work
          if npm publish --loglevel=verbose 2>/dev/null; then
            echo "✅ Successfully published to GitHub Packages"
          else
            echo "⚠️ GitHub Packages publish failed (this is optional - main npm publish succeeded)"
            echo "Package is available on npm registry: https://www.npmjs.com/package/buildworks-ai-decision-mcp"
          fi

      - name: Restore package.json
        run: mv -f package.npm.json package.json

